CREATE TABLE `spotify_picks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`artist_slug` text NOT NULL,
	`track_id` text NOT NULL,
	`title` text DEFAULT '' NOT NULL,
	`sort` integer DEFAULT 0 NOT NULL,
	`enabled` integer DEFAULT 1 NOT NULL,
	`created_by` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `spotify_picks_artist_track_uq` ON `spotify_picks` (`artist_slug`,`track_id`);--> statement-breakpoint
CREATE INDEX `spotify_picks_enabled_idx` ON `spotify_picks` (`enabled`,`sort`);
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `cv_spotify_picks_insert` AFTER INSERT ON `spotify_picks` BEGIN UPDATE `content_version` SET `v` = `v` + 1 WHERE `id` = 1; END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `cv_spotify_picks_update` AFTER UPDATE ON `spotify_picks` BEGIN UPDATE `content_version` SET `v` = `v` + 1 WHERE `id` = 1; END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `cv_spotify_picks_delete` AFTER DELETE ON `spotify_picks` BEGIN UPDATE `content_version` SET `v` = `v` + 1 WHERE `id` = 1; END;
--> statement-breakpoint
-- 首批推薦歌曲（2026-09-29）：Spotify 藝人嵌入頁的熱門歌曲，每位 3～5 首，只取該藝人主唱或列名第一的歌
INSERT OR IGNORE INTO `spotify_picks` (`artist_slug`, `track_id`, `title`, `sort`) VALUES
  ('chen-xian-jing', '6ys5ZWv1RTBlwBs1vRFyd1', 'Wui229', 0),
  ('chen-xian-jing', '5u6xwrIwh9cPW9VXCODU7v', '如果每天都可以 happy happy 誰想要sad:))', 1),
  ('chen-xian-jing', '4PwO55sEmOZr89pNhCUFuY', 'New notes', 2),
  ('chen-xian-jing', '6JHNsajzqfEBEcqm9nvb7Z', 'Wui (arranged by Charles Chang)', 3),
  ('chen-xian-jing', '1G6oFGVf2BoXfmKruxSSRb', '輕輕 (Original)', 4),
  ('chunyan', '57O1jU5BjDIlspvuyij6kC', '隔壁的姊姊', 5),
  ('chunyan', '27S802wgSxCeGz9NmIdLLa', 'Coco', 6),
  ('chunyan', '25pYFi4Wo1goEvYwuq4DDs', '你要我 - Cook the Vibe Version', 7),
  ('chunyan', '7LQ8cgodeEWaAqWqb5tVkY', '麻煩你了喔', 8),
  ('chunyan', '2qIisN8jmeZIQ2tFiHPCh2', '88的車', 9),
  ('double-j', '1jlysQj6clVSf5tEAReCve', '當我成了妳', 10),
  ('double-j', '4liZrrKSM0Ka9mD1ehpNYq', 'I''m a rapper - Demo Ver.', 11),
  ('double-j', '0oouMpECEKMMxUd141ecYV', '走遠 - Demo Ver.', 12),
  ('double-j', '4RBORVKjmg1BKgmY2NMzwL', 'Soul Searching', 13),
  ('double-j', '6kOeoVygdKhPJGfUl6YMvm', '再見', 14),
  ('e-so', '3yWMv4KSXoh1l61cAqykl1', 'Something I Don''t Need', 15),
  ('e-so', '4E5PyVOBH25CICgTURwGXM', 'CHANGE', 16),
  ('e-so', '3Bij7rScgMAWeCXpA3qJk9', '太陽', 17),
  ('e-so', '5QbK5PrR9wbog3M5vVAn2n', '她沒在看我', 18),
  ('e-so', '3MXio1CBF3ukhBtx9aURWM', 'I Wish I Was There', 19),
  ('gordon', '4dDTfanIuKXjZQYhGaRk71', 'Yesterday', 20),
  ('gordon', '1pd0JatWBUBH4XEkxA1S89', '飛行少女 Gina', 21),
  ('gordon', '5NYMKEcaapPQdxu1jFdveW', '睡吧寶貝', 22),
  ('gordon', '07PRLLU7s6EK6hUIAKstv5', '偷走', 23),
  ('gordon', '4Ks1TfNgAE55rbfCz4GvNs', 'Like You', 24),
  ('guts', '7L4WcYnU9KhCqfzYTaKenr', '迷途羔羊', 25),
  ('guts', '11mB5vkSy4HeR6ROPNAYzW', 'FLY OUT', 26),
  ('guts', '7nqDJEovkyjoWzKApVHkN2', 'COMING HOME', 27),
  ('guts', '0gMvHaaVQyQuqtcW2p9TZL', '把最甜的都給妳', 28),
  ('guts', '4GSOTzKLQHCDEhFNtFmRjl', '搖落', 29),
  ('kenzy', '4NoQV4KLLZvqg9JHufdTZL', '愛到才知痛', 30),
  ('kenzy', '1695S67wqNhC0Bitj043ra', '大丈夫', 31),
  ('kenzy', '1A5GjilDmBWIyekeyRldDD', '不想醒來', 32),
  ('kenzy', '3izgR8K6EbC7RU5gmY2F4c', '保險櫃', 33),
  ('kenzy', '0V3Xa568oOTBtUPBpgGSfq', '香火', 34),
  ('leo', '3NYy88OXh6mv6hpiYCk3XU', '長大十八歲', 35),
  ('leo', '6a8iS50yTXACRsQrKR9tGg', '最後一張紙 feat. ?', 36),
  ('leo', '0TgWgW2UYFctTDdN4GC6B7', '快樂的甘蔗人', 37),
  ('leo', '4w99eXGKJ64oxJSNF9tPNs', '陪妳過假日', 38),
  ('leo', '6Uy0XOFJC3cxAxdTIQNLKI', '得意的一天 A no is a no ft. 陳嫺靜 - Netflix《人選之人—造浪者》片尾曲', 39),
  ('li-ying-hong', '41sJNiLh96NJPH6OGfytyX', '台北直直撞', 40),
  ('li-ying-hong', '3py9gBgsoeVAmKMNT4oGH2', '龍虎豹', 41),
  ('li-ying-hong', '21rtnUfUA531PsCZHo9AUl', '什麼時候她 feat. 蛋堡Soft Lipa', 42),
  ('li-ying-hong', '2AAYnYULI81vR3njSo2oVp', 'Nina來台東', 43),
  ('li-ying-hong', '3ho7TfQryjbWUH3t8e6ooy', '水哥 ft. 蛋堡', 44),
  ('mc-hotdog', '6fADwOnsMmCM70OAxDF3fc', '差不多先生', 45),
  ('mc-hotdog', '3AWR7lmFL1PYL3afeeeMVp', '髒藝術家', 46),
  ('mc-hotdog', '1lcMyVPjYXaXpdWPYzrs76', '貧民百萬歌星', 47),
  ('mc-hotdog', '6AXBFFN1CgKiqHrT2fJ9lB', '樓上的房東', 48),
  ('mc-hotdog', '29sgXiafZq3bSkSGoafvli', '輕熟女27', 49),
  ('miss-ko', '0g3xY2ZkGUsVv9izhZk8y2', '皇后區的皇后', 50),
  ('miss-ko', '0DF6ogOpB1CYZF0PlG7WdR', '就改天', 51),
  ('miss-ko', '5zvE5C2JislfFqefghan0H', 'got.to.believe', 52),
  ('miss-ko', '70vBZH68qAPd3u9k17HRh7', 'homerun 全壘打', 53),
  ('miss-ko', '5R35Zx1fRR3oXKTQy5bqtf', 'b.ye 畢業', 54),
  ('mj116', '4M7VP5IiIj1saXNFINmxt3', 'SPOTLIGHT', 55),
  ('mj116', '1qrpfAFspxxhghnPeRHSsQ', 'Just Believe', 56),
  ('mj116', '6EE6lFjlQeERL683Ver4Po', '兄弟們要進城', 57),
  ('mj116', '72uecKUw0CCGWZCP7tzT0y', '辣台妹', 58),
  ('mj116', '5oPP4Sc6CFAD3SRsM8ZGe7', 'OGS', 59),
  ('muta', '36XrSk5yUQnBLDJqkddwwo', 'FatBoyGang', 60),
  ('muta', '2ncx7bgM5yuRIGXl0hpBPd', '過得爽爽', 61),
  ('muta', '7dQu7nnL62lcYJWiO0FGot', '肥男幫', 62),
  ('muta', '73re4Y4IwsMRe2W6iRaxBe', '蘇菲阿姨', 63),
  ('muta', '1Pk3xUCBf6dm9dfYHuwNGV', '一拜', 64),
  ('soft-lipa', '13tJ9Mkj7cjXxrTjOh0LAN', '關於小熊', 65),
  ('soft-lipa', '7Mlo3IR7Vz6GDrC9733KRz', 'I Want You', 66),
  ('soft-lipa', '10EbcvamEVm3t32nUj8lX1', '收斂水', 67),
  ('soft-lipa', '3dBd4ZCkpr1NPOaTXSZY3W', '過程', 68),
  ('soft-lipa', '49gm0W9gCb9dSaFZQYJQsh', 'Hit the Rhyme', 69),
  ('sowut', '2lkqAdyHV0AySf6Lnjkb5Q', 'wutever Pt. 2', 70),
  ('sowut', '6k0QxX9mUbr8G1OdtlQltG', 'MOLLYWANG', 71),
  ('sowut', '2LrOt9iIfaZcc2PDZFeTd0', 'TK17', 72),
  ('dj-mr-gin', '4AFoRvmyt1rRWNdZ6zrPu0', '少年ㄟ安啦', 73),
  ('dj-mr-gin', '1KO9yTWXOQry37BT5wB6EU', 'Aniki', 74),
  ('dj-mr-gin', '4CjjstJMq2RvbGtVtcFtuC', '格', 75),
  ('dj-mr-gin', '02Y30s6wMdssQVQkyXEAHL', 'YA生活', 76),
  ('dj-mr-gin', '22Jar9rrJwaTXw6nG9ZZHM', '沒毛病 ft. Jimmy boy', 77),
  ('sunset-rollercoaster', '7npPPrZEDmeHMk6mxvIeFa', 'My Jinji', 78),
  ('sunset-rollercoaster', '3jgZYDYIEthcx7BrDOzPCl', 'Bluebird', 79),
  ('sunset-rollercoaster', '1YTzatjgpsZVPMrNXa9r2Y', 'I Know You Know I Love You', 80),
  ('sunset-rollercoaster', '6ltbHDkQkO9uWVl4XZ3qeC', 'Humor Tumor', 81),
  ('sunset-rollercoaster', '4uOlsE5ivyrFxtY0nGhmoK', 'Wind of Tomorrow', 82),
  ('zhang-zhen-yue', '2fc2vUA5H3mTAr9rQoBDKt', '愛我別走', 83),
  ('zhang-zhen-yue', '4cOagvJS8xGFU4VLpcp0gK', '浪人的…', 84),
  ('zhang-zhen-yue', '2wxSjPX7frBeeTaoqvhU10', '小宇', 85),
  ('zhang-zhen-yue', '513YbEM3Cca6G4txHhNIKO', '搬家', 86),
  ('zhang-zhen-yue', '14AgBbjVYu2l5vWvbb9XVi', '再見', 87),
  ('li-quan-zhe', '1Rhe2zOguwPW64NzxEM4Uk', '滾開', 88),
  ('li-quan-zhe', '5bUyFnwiy8khTZFaYdr6at', '颱風要來了', 89),
  ('li-quan-zhe', '5WqcNOMfcbLjoHEHxmhqCp', '我愛你是一輩子的事', 90),
  ('li-quan-zhe', '54kG5Bhd3bsRQNBYFFgOrc', '看到你我就歡喜', 91),
  ('li-quan-zhe', '3D65szOpJZ1eEbhQORbo8W', '兩顆星星', 92);
